### ping
GET http://localhost:8001/api/ping HTTP/1.1
content-type: application/json

### list
GET http://localhost:8001/api/invoice HTTP/1.1
content-type: application/json

### show
GET http://localhost:8001/api/invoice/show/85468be8-1a79-489a-823a-f1e61ed63f16 HTTP/1.1
content-type: application/json

### approve
POST http://localhost:8001/api/invoice/approve HTTP/1.1
content-type: application/json

{
    "id": "85468be8-1a79-489a-823a-f1e61ed63f16"
}

### reject
POST http://localhost:8001/api/invoice/reject HTTP/1.1
content-type: application/json

{
    "id": "85468be8-1a79-489a-823a-f1e61ed63f16"
}