services:

    app:
        build: .docker/php
        container_name: approval_app
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - approval_net
        depends_on:
            - db

    nginx:
        build: .docker/nginx
        container_name: approval_nginx
        restart: always
        tty: true
        ports:
            - "8001:80"
        volumes:
            - .:/var/www
        networks:
            - approval_net
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        container_name: approval_db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=approval_db
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - approval_net

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: approval_phpmyadmin
        restart: always
        tty: true
        ports:
            - "8002:80"
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=root
        networks:
            - approval_net
        depends_on:
            - db
            - nginx

networks:
    approval_net:
        driver: bridge
