name: PHPCS

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, pdo, pdo_mysql, bcmath
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Run PHP Code Sniffer
        run: vendor/bin/phpcs --standard=PSR12 app/
